GEMINI_API_KEY = "AIzaSyDoG1iBuXynXWhIVdG3s93js9AlTDsWkYs"

[gcp_service_account]
type = "service_account"
project_id = "gen-lang-client-0883242491"
private_key_id = "c7cc16e8a8f0d19ab431339c3fafdbbbeb33de2d"
private_key = """
-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCSKMg+bR2KNFLb
8z1COY6qq2r/+JjGtdNidsrNSJRNFvx2PbU8zz1UiopmFCaB88Khqae2okz3/VrA
z4RpNCfwuQr2mNl9FPkiwDRvTAVQQnEwBbq8GV6HSPU0dReL/S9a98zpq16xknk2
U5NXJumnPLDjyDpiDxgmRzSCZg7/QFjzPXlzeC9DNIyR8+vFdrWnBMXVxhOCTx/J
H+gSp65MotpyhthezWjW6yIFfK+oNrxGyNWps/PX9RKs2YFL20s0T++9g/qGFCX2
yvInOMM87My3T+hjIE+8OCdE8t39SFST1mpFVFplPOZlVbVDTDFWiH0tnLuIF2Cb
lW+Q2sRNAgMBAAECggEAGNFoeSMtlClg1XzWzs83sLbFRzw28uzufSZ3NsbnebSY
v1ook3AMNbYFnKI4zLGvv6QveIVUJPrmBV3nWbbTvl4pZKidK45bZIF3Fdv2fgOe
NR2P8P8szDOBAXyNeEWQXDW+G4JwJJ5eyzEDUJXosG9PiQoXkc2G1/8YxTifvMs2
Ta/bWjV1t0uymIDgjLdeH/j3uz8KknOG3xm812rzAzCazSkypTvhh1eIiR+WEA8p
dlkM7Jm2vvCPgp1MZYjBYHv8CK6P0SUCWU161OXLyLAwG9gE5NMr19kWkdDolP3q
2anJ6j6i0jRpMVvr0txNFxjGu8PzTo+vo80aPULsSQKBgQDN3+fBuOvZen0RXYXV
ibBPO4vUYrvDn2dnX9gijlwmPvizD+4hXJ8RijTbVZDqYqZM6yFYtYg9fFcNeYlP
mzfFLrM0CyYB+HOXYNqn5OlnAxCjPZv4/64OyGjQ6ea7y229WtjywIpfsbrv/P1f
Ogg+vHCmLwwJM9LefMTamrxBCQKBgQC1vtdgQKVUy3NTv1fqPyiXvsOPMqrY9Xwa
gtX7JfJj/B77g+JT+cQ6BXLHJv1TEvAGJYqlS2OiVDPoSo7XRNMZUfBL8s/gtz8Q
YaoxNb2oL/IZ+ytaEdqBnh0p2woN05fHGVI5py33h73y/DcozA2kER2liKJT8P3l
pNnLVHfuJQKBgQCFfqrI8x/75XEz0XD3BlFND0+caGlYcASdA4ki3yzhn/OkKLBA
8c4zkWq0zscpNM6hEdaNryiotfe8xRJEjGGdeqq5FIGQxYounp8qP0UZhuNC9rAs
xZ4X99v/m6wCGecO4dnLjw4q/xQ4idPB699szsQ8/kTPsssJed4r4iowAQKBgAyO
kvLjhIjHRcCTh893baaOV5SdO5Ch5WEviPlBNe4SjVFzWz/SEeywU63O09HZjRvf
nCSvgMLGbo+uFxBogO1O6/tTW2l7P7AyD0A3JlNofKGu6N/gO+iYtAsgRyGNbP8k
kLnLAzIG/ui65FS9RHQBerrlJdIG5IPpT+LsgxzBAoGAUhOEaFB+JDEMGljS8687
fcFer8gJzKMg527nc8Xgsw0r1a4jbWZaJzdluH815QeMWzDX4PE9hxtfT30yluPm
xJOSdxBnXWFdyvL1q3SAEehVNfDZGhcQQtOh454nRnhOzxSwOktNneR3wD7D9pPZ
xTZXfPtCIpgTBh7yjqurOR0=
-----END PRIVATE KEY-----
"""
client_email = "fynd-task@gen-lang-client-0883242491.iam.gserviceaccount.com"
client_id = "107830824873003316048"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/fynd-task%40gen-lang-client-0883242491.iam.gserviceaccount.com"
universe_domain = "googleapis.com"